---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-job
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-user
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: [ "secrets" ]
    verbs: ["*"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: [ "sparkapplications", "scheduledsparkapplications" ]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [ "pods/log" ]
    verbs: [ "get", "list" ]
  - apiGroups: [""]
    resources: [ "pods/portforward" ]
    verbs: [ "get", "list", "create" ]
#  - apiGroups: ['policy']
#    resources: ['podsecuritypolicies']
#    verbs:     ['use']
#    resourceNames: ["privileged"]   # WARNING: "provileged' is for test only.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-job
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.spark.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: spark-job
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-user
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.spark.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: spark-user
  apiGroup: rbac.authorization.k8s.io
