---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: psp:kafka-cluster
rules:
- apiGroups:
  - policy
  resourceNames:
  - kafka-cluster
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:kafka-cluster:{{ template "kafkaCluster.clusterName" . }}-zookeeper
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:kafka-cluster
subjects:
- kind: ServiceAccount
  name: {{ template "kafkaCluster.clusterName" . }}-zookeeper
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: {{ template "kafkaCluster.clusterName" . }}-kafka
  namespace: {{ .Release.Namespace }}
  