
gha2s3:
  image: ghcr.io/gha2/gha2s3:latest

  # Must be 'minio' or 'aws'
  s3Type:

  # Only relevant for minio
  # s3Url:

  # When s3 is accessed using minio or aws IAM account
  # accessKey:
  # secretKey:

  # When s3 is accessed with an assumed IAM role
  # assumeRole:

  # Default: "gha2s3-{year:04d}"
  # bucketFormat:

  # Default: "{year:04d}/{month:02d}/{day:02d}/{hour:02d}.json.gz"
  # objectFormat:

  # Default: 0
  # backDays:

  # On a file not found, if more recent than now - tolerationHours, this is a 'normal' case (Just wait).
  # Otherwise, display an error
  # Default: 6
  # tolerationHours:

  # Max successive download on one shot
  # Default: 1000000
  # maxDownloads:

  # If >0, enter an infinite loop, with a shot every 'waitSeconds'
  # Default: 0
  # waitSeconds:

  # namespace/name of a secret hosting a CA validating S3 server certificate.
  # ca: cert-manager/cluster-issuer1-ca

  # When an error occurs, wait 'waitOnError' seconds before exiting. (Give some time to check the logs
  waitOnError: 120

  # Command line debugging
  # set_x: yes