---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace  }}
type: Opaque
data:
  encryptedPostgresPassword: {{ .Values.postgres.encryptedPostgresPassword | b64enc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  namespace: {{ .Release.Namespace  }}
  labels:
    app: postgres
spec:
  storageClassName: {{ .Values.postgres.storage.class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "postgres.storage.size must be defined!" .Values.postgres.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Release.Namespace  }}
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image:  postgres:9.6-alpine
          env:
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: encryptedPostgresPassword
                  name: postgres-secret
          volumeMounts:
            - mountPath: /data
              name: postgres-data
      securityContext:
        runAsUser: 70
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace  }}
{{ if and (.Values.postgres.metallb.enabled) (.Values.postgres.metallb.ipSharingKey) }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Values.postgres.metallb.ipSharingKey }}
{{ end}}
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.servicePort }}
      targetPort: 5432
{{ if .Values.postgres.metallb.enabled }}
  type: LoadBalancer
{{ end }}
{{ if and (.Values.postgres.metallb.enabled) (.Values.postgres.metallb.externalIp) }}
  loadBalancerIP:   {{ .Values.postgres.metallb.externalIp }}
{{ end }}
