{{ if .Values.gha2s3.ca}}

apiVersion: v1
kind: Secret
metadata:
  name: gha2s3-ca
  annotations:
    replicator.v1.mittwald.de/replicate-from: {{ .Values.gha2s3.ca }}
data: {}
  #ca.crt: ""

{{ end }}
