{{ if .Values.gha2s3.accessKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gha2s3-secret
type: Opaque
data:
  accessKey: {{ .Values.gha2s3.accessKey | b64enc }}
  secretKey: {{ .Values.gha2s3.secretKey | b64enc }}

{{ end }}
