apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-gha2minio
  namespace: argocd
spec:
  source:
    path: apps/gha/gha2minio
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        minio:
          server: minio.minio1.svc
          accessKey: minio
          secretKey: minio123
        gha2minio:
          maxDownloads: 24
          waitSeconds: 30
          backDays: 0
          bucket: "gha-primary-1"
          objectFormat: "{year:04d}/{month:02d}/{day:02d}/{hour:02d}.json.gz"
          waitOnError: 300
  destination:
    namespace: gha1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

