apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-minio2kafka
  namespace: argocd
spec:
  source:
    path: apps/gha/minio2kafka
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        minio:
          server: minio.minio1.svc
          accessKey: minio
          secretKey: minio123
        rawtopic:
          clusterNamespace: kluster1
          cluster: kluster1
          name: gharaw1
          replicas: 1
          allowDelete: true
          config:
            retention.bytes: "1073741824"  # 1 GiB
            retention.ms: "-1"
            segment.bytes: "104857600"  # 100 MiB
        minio2kafka:
          bucket: "gharaw1"
          secondsAfterSuccess: 300 # 5 mn
          secondsAfterFailure: 3600 # One hour
  destination:
    namespace: gha1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

