apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  source:
    path: middlewares/spark/spark-operator
    repoURL: https://github.com/BROADSoftware/depack.git
  destination:
    namespace: spark-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

