apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi1
  namespace: argocd
spec:
  source:
    path: middlewares/kafka/strimzi
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        strimzi-kafka-operator:
          kubernetesServiceDnsDomain: kspray1.local
  destination:
    namespace: strimzi1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

