spark-operator:
  securityContext:
    runAsUser: 1001
  webhook:
    enable: true
  # See
  # - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1004
  # - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1058
  # - https://console.cloud.google.com/gcr/images/spark-operator/GLOBAL/spark-operator?gcrImageListsize=30
  # The 1.0.9 chart version still use an old image, without the fix describe above. So, force a more recent one.
  # Could also use 'lastest', but better to be in control
  image:
    tag: v1beta2-1.2.1-3.0.0