---
apiVersion: v1
kind: Secret
metadata:
  name: spark-history-server-secret
  namespace: {{ .Release.Namespace  }}
type: Opaque
data:
  s3AccessKey: {{ .Values.sparkHistoryServer.s3AccessKey | b64enc }}
  s3SecretKey: {{ .Values.sparkHistoryServer.s3SecretKey | b64enc }}

