---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: {{ .Release.Namespace  }}
  labels:
    app: spark-history-server
spec:
  ports:
    - port: 18080
      targetPort: http
      protocol: TCP
  selector:
    app: spark-history-server
