apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cerebro-kspray2-ctb01
  namespace: argocd
spec:
  source:
    path: apps/cerebro
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        ingressHost: cerebro.ingress.kspray2.ctb01
        clusterIssuer: cluster-issuer1        
  destination:
    namespace: cerebro
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

