


metastore:
  postgresPort: 15432
  logLevel: INFO
  s3Endoint: https://minio.minio1.svc
  s3AccessKey: minio
  s3SecretKey: minio123
  #s3RequestTimeOut: 5
  metallb:
    enabled: yes
    externalIp: 192.168.33.86
    ipSharingKey: tcp1

