apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: middlewares/opendistro.1.10.1
    repoURL: https://github.com/BROADSoftware/depack.git
    targetRevision: HEAD
    helm:
      values: |
        clusterIssuer: cluster-issuer1
        elasticsearch:
          ingressHost: elastic1.ingress.kspray1.ctb01
          master:
            replicas: 2
            persistence:
              storageClass: topolvm-ssd
              size:  8Gi
          data:
            replicas: 3
            persistence:
              storageClass: topolvm-hdd
              size:  10Gi
        kibana:
          ingressHost: kibana1.ingress.kspray1.ctb01
  destination:
    namespace: elastic1
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

