apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
spec:
  source:
    path: middlewares/filebeat-logging
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        processors:
          cloud:
            enabled: false
          host:
            enabled: true
        output:
          elasticsearch:
            enabled: true
            url:  https://elastic1.ingress.kspray2.ctb01:443
            ssl_verification_mode: none
            user: admin
            password: admin
  destination:
    namespace: filebeat1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

