apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-json2parquet
  namespace: argocd
spec:
  source:
    path: apps/gha/json2parquet
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        json2parquet:
          schedule: "@every 1m"
          minio:
            serverUrl: https://minio.minio1.svc
            accessKey: minio
            secretKey: minio123
          driver:
            cores: 2
            coreLimit: "4"
            memory: "8G"
          executor:
            instances: 4
            cores: 2
            coreLimit: "4"
            memory: "8G"
  destination:
    namespace: spark1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=false

