apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-spark1
  namespace: argocd
spec:
  source:
    path: middlewares/spark/spark-namespace
    repoURL: https://github.com/BROADSoftware/depack.git
  destination:
    namespace: spark1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

