apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore
  namespace: argocd
spec:
  source:
    path: middlewares/hive-metastore
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        metastore:
          postgresPort: 5432
          logLevel: INFO
          s3Endoint: https://minio.minio1.svc
          s3AccessKey: minio
          s3SecretKey: minio123
          #s3RequestTimeOut: 5
          metallb:
            enabled: yes
            externalIp: 10.59.1.40
            ipSharingKey: tcp1
  destination:
    namespace: spark-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

