apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio2
  namespace: argocd
spec:
  source:
    path: apps/minio.3.0.28/tenant
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        zones:
          - storageClass: topolvm-hdd
            servers: 4
            volumesPerServer: 2
            storagePerVolume: 10Gi
            podAntiAffinity: false  # As we have only 3 nodes
        ingressHost: minio2.ingress.kspray1.ctb01
        console:
          enabled: false
          replicas: 1
          host: minio2-console.ingress.kspray1.ctb01
          adminLogin: YWRtaW4=   # (echo -n 'admin' | base64)
          adminPassword: YWRtaW4xMjM=   # (echo -n 'admin123' | base64)
  destination:
    namespace: minio2
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

