apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio1
  namespace: argocd
spec:
  source:
    path: middlewares/minio.3.0.28/tenant
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        clusterDomain: kspray1.ctb01
        ingressHost: minio1.ingress.kspray1.ctb01
        clusterIssuer: cluster-issuer1
        zones:
          - storageClass: topolvm-ssd
            servers: 4
            volumesPerServer: 1
            storagePerVolume: 100Gi
            podAntiAffinity: true
        console:
          enabled: false
          replicas: 1
          host: minio1-console.ingress.kspray1.ctb01
          adminLogin: YWRtaW4=   # (echo -n 'admin' | base64)
          adminPassword: YWRtaW4xMjM=   # (echo -n 'admin123' | base64)
  destination:
    namespace: minio1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

