apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  source:
    path: middlewares/minio.3.0.28/operator
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        clusterDomain: kspray1.ctb01
  destination:
    namespace: minio-operator
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

