apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  source:
    path: middlewares/postgresql/server
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        postgres:
          servicePort: 5432
          storage:
            class: topolvm-nvme
            size: 500M
          metallb:
            enabled: yes
            externalIp: 10.59.1.40
            ipSharingKey: tcp1
  destination:
    namespace: postgres
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

