apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-kspray1-ctb01
  namespace: argocd
spec:
  source:
    path: apps/kube-prometheus-stack
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        prometheus:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              cert-manager.io/cluster-issuer: cluster-issuer1
            hosts:
            - prometheus.ingress.kspray1.ctb01
            tls:
            - hosts:
                - prometheus.ingress.kspray1.ctb01
              secretName: prometheus-tls            
          prometheusSpec:    
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: topolvm-ssd
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          adminPassword: admin
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              cert-manager.io/cluster-issuer: cluster-issuer1
            hosts:
            - grafana.ingress.kspray1.ctb01
            tls:
            - hosts:
                - grafana.ingress.kspray1.ctb01
              secretName: grafana-tls
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

