apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-history-server
  namespace: argocd
spec:
  source:
    path: middlewares/path/history-server
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        sparkHistoryServer:
          s3Endoint: https://minio.minio1.svc
          s3AccessKey: minio
          s3SecretKey: minio123
          clusterIssuer: cluster-issuer1
          ingressHost: spark-history-server.ingress.kspray1.ctb01
          imagePullPolicy: Always
  destination:
    namespace: spark-history-server
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

