---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events
  namespace: {{ .Release.Namespace  }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace  }}
  name: argo-events
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "update", "get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "watch", "update", "patch", "get", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["create", "update", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events
  namespace: {{ .Release.Namespace  }}
subjects:
  - kind: ServiceAccount
    name: argo-events
    apiGroup: ""
roleRef:
  kind: Role
  name: argo-events
  apiGroup: rbac.authorization.k8s.io