# Value for minio1.server 
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-server
type: Opaque
data:
  server: {{ required "A 'minio.server' value is required" .Values.minio.server }}
  accessKey: {{ required "An 'minio.accessKey' value is required" .Values.minio.accessKey }}
  secretKey: {{ required "A 'minio.secretKey' value is required" .Values.minio.secretKey }}

