# Value for minio1.server 
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-server
type: Opaque
data:
  server: {{ .Values.minio.server | b64enc }}
  accessKey: {{ .Values.minio.accessKey | b64enc }}
  secretKey: {{ .Values.minio.secretKey | b64enc }}

