# Value for minio1.server 
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-server
type: Opaque
data:
  server: {{ required .Values.server }}
  accessKey: {{ required .Values.accessKey }}
  secretKey: {{ required .Values.secretKey }}

