# Value for minio1.server 
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-server
type: Opaque
data:
  server: {{ required "A 'server' value is required" .Values.server }}
  accessKey: {{ required "An 'accessKey' value is required" .Values.accessKey }}
  secretKey: {{ required "A 'secretKey' value is required" .Values.secretKey }}

