# rawtopic
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .Values.rawtopic.name }}
  namespace: {{ .Values.rawtopic.clusterNamespace  }}
  #namespace: {{ .Release.Namespace  }}
  labels:
    strimzi.io/cluster: {{ required "'rawtopic.cluster' must be defined!" .Values.rawtopic.cluster }}
{{ if not .Values.rawtopic.allowDelete }}
  annotations:
    "helm.sh/resource-policy": keep
{{ end }}
spec:
  partitions: {{ .Values.rawtopic.partitions }}
  replicas: {{ .Values.rawtopic.replicas }}
  config:
{{- $defaultConfig :=  dict "retention.bytes" "10737418240" "retention.ms" "-1" "segment.bytes" "1073741824" -}}
{{- range $key, $val := merge (.Values.rawtopic.config|default dict ) $defaultConfig  }}
    {{ $key }}: {{ $val | quote }}
{{- end }}


