apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kluster1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: middlewares/kafka/cluster
    repoURL: https://github.com/BROADSoftware/depack.git
    targetRevision: HEAD
    helm:
      values: |
        clusterName: kluster1
        kafka:
          replicas: 3
          config:
            offsets.topic.replication.factor: 3
            transaction.state.log.replication.factor: 3
            transaction.state.log.min.isr: 2
            auto.create.topics.enable: false
            delete.topic.enable: true
          listeners:
            plain: {}
            external:
              type: loadbalancer
              tls: false
          jmx:
            enabled: true
          storage:
            size: 20Gi
            class: topolvm-hdd
        zookeeper:
          replicas: 3
          storage:
            size: 2Gi
            class: topolvm-nvme
        akhq:
          enabled: true
          clusterIssuer: cluster-issuer1
          ingressHost: akhq1.ingress.kspray3.ctb01
        cmak:
          enabled: true
          clusterIssuer: cluster-issuer1
          ingressHost: cmak1.ingress.kspray3.ctb01
        zkdoor:
          enabled: true
          loadBalancer: true
  destination:
    namespace: kluster1
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

