# Value for minio1.server 
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-server
type: Opaque
data:
  serverUrl: {{ .Values.json2parquet.minio.serverUrl | b64enc }}
  accessKey: {{ .Values.json2parquet.minio.accessKey | b64enc }}
  secretKey: {{ .Values.json2parquet.minio.secretKey | b64enc }}

