---
# Based on restricted policy, with hostPath added
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: filebeat-logging
spec:
  allowPrivilegeEscalation: false
  forbiddenSysctls:
    - '*'
  fsGroup:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  hostNetwork: true
  requiredDropCapabilities:
    - ALL
  runAsUser:
    rule: RunAsAny   # Was MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  volumes:
    - configMap
    - emptyDir
    - projected
    - secret
    - downwardAPI
    - persistentVolumeClaim
    - hostPath              # Added
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: filebeat
  name: psp:filebeat-logging
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups:
      - policy
    resourceNames:
      - filebeat-logging
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:filebeat-logging:filebeat
  namespace: filebeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:filebeat-logging
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: filebeat

