---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: filebeat
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    # To enable hints based autodiscover, remove `filebeat.inputs` configuration and uncomment this:
    #filebeat.autodiscover:
    #  providers:
    #    - type: kubernetes
    #      node: ${NODE_NAME}
    #      hints.enabled: true
    #      hints.default_config:
    #        type: container
    #        paths:
    #          - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
    {{ if .Values.processors.cloud.enabled }}- add_cloud_metadata:{{ end }}
    {{ if .Values.processors.host.enabled }}- add_host_metadata:{{ end }}

    {{- if .Values.processors.cloud.enabled }}
    cloud.id: {{ .Values.processors.cloud.id }}
    cloud.auth: {{ .Values.processors.cloud.auth }}
    {{ end }}

  {{- if .Values.output.elasticsearch.enabled}}

    output.elasticsearch:
      hosts: ['{{ .Values.output.elasticsearch.url }}']
      ssl.verification_mode: {{ .Values.output.elasticsearch.ssl_verification_mode }}
      username: {{.Values.output.elasticsearch.user }}
      password: {{ .Values.output.elasticsearch.password }}
  {{- end }}

    setup.ilm.enabled: false
    setup.ilm.check_exists: false  
