apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-event
  namespace: argocd
spec:
  source:
    path: middlewares/argo-events.1.1.0
    repoURL: https://github.com/BROADSoftware/depack.git
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

