apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha1
  namespace: argocd
spec:
  source:
    path: apps/gha
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        maxDownloads: 2
        waitSeconds: 30
        backDays: 1
        bucketFormat: "gha12minio-{year:04d}"
        objectFormat: "{year:04d}/{month:02d}/{day:02d}/{hour:02d}.json.gz"
        waitOnError: 60
  destination:
    namespace: gha1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

