apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kluster1-kspray2-local
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/kafka/cluster
    repoURL: https://github.com/BROADSoftware/depack.git
    targetRevision: HEAD
    helm:
      values: |
        clusterName: kluster1
        kafka:
          replicas: 3
          config:
            offsets.topic.replication.factor: 1
            transaction.state.log.replication.factor: 1
            transaction.state.log.min.isr: 1
          listeners: |-
            plain: {}
            external:
              type: loadbalancer
              tls: false
          storage:
            size: 5Gi
            class: topolvm-tlvm1
        zookeeper:
          storage:
            size: 2Gi
            class: topolvm-tlvm1
  destination:
    namespace: kluster1
    server: https://kubernetes.default.svc
#  syncPolicy:
#    syncOptions:
#    - CreateNamespace=true

