apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opendistro1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/opendistro.1.10.1
    repoURL: https://github.com/BROADSoftware/depack.git
    targetRevision: HEAD
    helm:
      values: |
        elasticsearch:
          master:
            replicas: 1
            persistence:
              storageClass: topolvm-tlvm1
              size:  2Gi
          data:
            replicas: 1
            persistence:
              storageClass: topolvm-tlvm1
              size:  10Gi
          client:
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: "nginx"
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                cert-manager.io/cluster-issuer: cluster-issuer1
              hosts:
                - elastic1.shared1
              tls:
              - secretName: elastic-tls
                hosts:
                - elastic1.shared1
        kibana:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              cert-manager.io/cluster-issuer: cluster-issuer1
            hosts:
            - kibana1.shared1
            tls:
            - secretName: kibana-tls
              hosts:
              - kibana1.shared1            
  destination:
    namespace: opendistro1
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

