apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/opendistro.1.10.1
    repoURL: https://github.com/BROADSoftware/depack.git
    targetRevision: HEAD
    helm:
      values: |
        clusterIssuer: cluster-issuer1
        elasticsearch:
          ingressHost: elastic1.shared1
          master:
            replicas: 1
            persistence:
              storageClass: topolvm-tlvm1
              size:  2Gi
          data:
            replicas: 1
            persistence:
              storageClass: topolvm-tlvm1
              size:  10Gi
        kibana:
          ingressHost: kibana1.shared1
  destination:
    namespace: elastic1
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

