apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    path: middlewares/kube-prometheus-stack
    repoURL: https://github.com/BROADSoftware/depack.git
    helm:
      values: |
        prometheus:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              cert-manager.io/cluster-issuer: cluster-issuer1
            hosts:
            - prometheus.shared1
            tls:
            - hosts:
                - prometheus.shared1
              secretName: prometheus-tls
          prometheusSpec:    
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: topolvm-tlvm1
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
        grafana:
          adminPassword: admin
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              cert-manager.io/cluster-issuer: cluster-issuer1
            hosts:
            - grafana.shared1
            tls:
            - hosts:
                - grafana.shared1
              secretName: grafana-tls
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

