---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-controller
  namespace: topolvm-system
  labels:
    app: prometheus-topolvm-controller
spec:
  selector:
    app.kubernetes.io/name: controller
  ports:
    - protocol: TCP
      name: prometheus
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-node
  namespace: topolvm-system
  labels:
    app: prometheus-topolvm-node
spec:
  selector:
    app.kubernetes.io/name: node
  ports:
    - protocol: TCP
      name: prometheus
      port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-topolvm-controller
  namespace: prometheus
spec:
  namespaceSelector:
    matchNames:
      - topolvm-system
  selector:
    matchLabels:
      app: prometheus-topolvm-controller
  endpoints:
    - port: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-topolvm-nodes
  namespace: prometheus
spec:
  namespaceSelector:
    matchNames:
      - topolvm-system
  selector:
    matchLabels:
      app: prometheus-topolvm-node
  endpoints:
    - port: prometheus


