# Value for minio1.server 
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-server
type: Opaque
data:
  server: bWluaW8ubWluaW8xLnN2Yy5rc3ByYXkyLmxvY2FsCg==  # minio.minio1.svc.kspray2.local
  accessKey: bWluaW8K                                   # minio
  secretKey: bWluaW8xMjMK                               # minio123