{{ if .Values.clusterIssuer}}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-minio
  namespace:  {{ .Release.Namespace }}  
spec:
  commonName: {{ .Values.ingressHost }}
  secretName: tls-minio
  dnsNames:
    # Ingress domain
    - {{ .Values.ingressHost }}
    # Internal domain
    - "minio.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
    - "*.{{ template "minio.tenantName" . }}-hl.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
    - "*.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
    - "minio.{{ .Release.Namespace }}.svc"
    - "*.{{ template "minio.tenantName" . }}-hl.{{ .Release.Namespace }}.svc"
    - "*.{{ .Release.Namespace }}.svc"
  issuerRef:
    name: {{ .Values.clusterIssuer }}
    kind: ClusterIssuer
{{ end }}    
    