
sparkHistoryServer:
  # To fulfill in specifics values file
  s3Endoint:
  s3AccessKey:
  s3SecretKey:
  ingressHost:
  clusterIssuer:
  # Default
  imagePullPolicy: IfNotPresent
  logLevel: INFO
  eventLogDir: s3a://spark/eventlogs
  replicas: 2
  cleaner:
    enabled: true
    interval: 1d
    maxAge: 7d


