elasticsearch:
  master:
    replicas: 2
    persistence:
      storageClass: topolvm-ssd
      size:  8Gi
  data:
    replicas: 3
    persistence:
      storageClass: topolvm-hdd
      size:  10Gi
kibana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
    - kibana1.kspray1.ctb01
